spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/nicety
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

mail:
  host: smtp.mail.yahoo.com
  port: 587
  starttls: true
  auth: true
  fromEmail: nicety_main@yahoo.com
  appPassword: sfzycofbckaebyhn

