spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/nicety
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 394442828587-rg4pber3p0ra0uiemsj5ouj57rnbau5i.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

mail:
  host: smtp.mail.yahoo.com
  port: 587
  starttls: true
  auth: true
  fromEmail: nicety_main@yahoo.com
  appPassword: sfzycofbckaebyhn



